//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_rabota_3
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Спр препод.
    /// </summary>
    // *** Start programmer edit section *** (СпрПрепод CustomAttributes)

    // *** End programmer edit section *** (СпрПрепод CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник преподаватели")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СпрПреподE", new string[] {
            "Фио as \'Фио преподавателя\'"})]
    [View("СпрПреподL", new string[] {
            "Фио as \'Фио преподавателя\'"})]
    public class СпрПрепод : ICSSoft.STORMNET.DataObject
    {
        
        private string fФио;
        
        // *** Start programmer edit section *** (СпрПрепод CustomMembers)

        // *** End programmer edit section *** (СпрПрепод CustomMembers)

        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (СпрПрепод.Фио CustomAttributes)

        // *** End programmer edit section *** (СпрПрепод.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (СпрПрепод.Фио Get start)

                // *** End programmer edit section *** (СпрПрепод.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (СпрПрепод.Фио Get end)

                // *** End programmer edit section *** (СпрПрепод.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СпрПрепод.Фио Set start)

                // *** End programmer edit section *** (СпрПрепод.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (СпрПрепод.Фио Set end)

                // *** End programmer edit section *** (СпрПрепод.Фио Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СпрПреподE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрПреподE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрПреподE", typeof(IIS.Kursovaya_rabota_3.СпрПрепод));
                }
            }
            
            /// <summary>
            /// "СпрПреподL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СпрПреподL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СпрПреподL", typeof(IIS.Kursovaya_rabota_3.СпрПрепод));
                }
            }
        }
    }
}
